# CMS Backend - App Engine Configuration
runtime: nodejs20
service: cms-dev

# Instance configuration
instance_class: F2  # 256MB RAM, 600MHz CPU

# Environment variables
env_variables:
  NODE_ENV: "production"
  APP_ENVIRONMENT: "development"
  HOST: "0.0.0.0"
  PORT: "8080"
  DATABASE_CLIENT: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "jjelevate"
  DATABASE_USERNAME: "jjelevate_app"
  DATABASE_SSL: "false"
  DATABASE_HOST: "/cloudsql/secret-rope-485200-h6:northamerica-northeast2:jjelevate-dev-db"
  DATABASE_PASSWORD: "UPDATE_WITH_YOUR_DB_PASSWORD"
  JWT_SECRET: "UPDATE_WITH_YOUR_JWT_SECRET"
  ADMIN_JWT_SECRET: "UPDATE_WITH_YOUR_ADMIN_JWT_SECRET"
  APP_KEYS: "UPDATE_WITH_YOUR_APP_KEYS"
  API_TOKEN_SALT: "UPDATE_WITH_YOUR_API_TOKEN_SALT"
  TRANSFER_TOKEN_SALT: "UPDATE_WITH_YOUR_TRANSFER_TOKEN_SALT"
  GOOGLE_CLIENT_ID: "UPDATE_WITH_YOUR_GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "UPDATE_WITH_YOUR_GOOGLE_CLIENT_SECRET"
  PUBLIC_URL: "https://cms-dev-dot-secret-rope-485200-h6.nn.r.appspot.com"
  CLIENT_PORTAL_URL: "https://portal.jjelevate.com"
  JJ_PORTAL_CAPTCHA_SECRET: "UPDATE_WITH_YOUR_CAPTCHA_SECRET"
  EMAIL_PROVIDER: "google"
  GOOGLE_SMTP_USER: "noreply@jjelevateas.com"
  GOOGLE_APP_PASSWORD: "UPDATE_WITH_YOUR_GOOGLE_APP_PASSWORD"
  SMTP_FROM: "noreply@jjelevateas.com"
  SMTP_REPLY_TO: "admin@citysoftsolutions.com"
  GCP_PROJECT_ID: "secret-rope-485200-h6"
  GCS_BUCKET_NAME: "jjelevate-development-documents"
  # Redis configuration (update REDIS_HOST after creating Memorystore instance)
  REDIS_HOST: "UPDATE_WITH_REDIS_IP"
  REDIS_PORT: "6379"

# VPC Connector for Redis access (create with: gcloud compute networks vpc-access connectors create)
vpc_access_connector:
  name: "projects/secret-rope-485200-h6/locations/northamerica-northeast2/connectors/jjelevate-connector"
  egress_setting: private-ranges-only

# Auto-scaling configuration
automatic_scaling:
  min_instances: 0        # Scale to zero when no traffic
  max_instances: 3        # Max instances for dev
  min_idle_instances: 0   # No idle instances (cost saving)
  max_idle_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

# Health check
liveness_check:
  path: "/_health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Cloud SQL connection (Toronto, Canada - northamerica-northeast2)
beta_settings:
  cloud_sql_instances: "secret-rope-485200-h6:northamerica-northeast2:jjelevate-dev-db"

# Build configuration
build_env_variables:
  NODE_ENV: "production"
